const data = {
  count: 178647,
  results: [
    {
      id: "b84a8a00-7517-4993-8a17-7af1b1ca3c23",
      sku: "CT8012-116",
      brand: "Jordan",
      name: "Air Jordan 11 Retro 'Cherry'",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 11",
      releaseYear: "2022",
      releaseDate: "2022-12-10",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story:
        "The Air Jordan 11 Retro ‘Cherry’ showcases familiar two-tone color blocking that recalls the low-top AJ11 ‘Varsity Red’ from 2001. The upper is crafted from white ballistic mesh with tonal webbing eyelets and a shiny patent leather mudguard in a bold scarlet hue. Matching red accents land on the interior collar and an embroidered Jumpman on the white leather heel overlay. Lightweight cushioning arrives via a plush Phylon midsole, supported underfoot by a carbon fiber spring plate and a translucent rubber outsole.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-11-retro-cherry-ct8012-116",
        flightClub:
          "https://flightclub.com/air-jordan-11-retro-cherry-ct8012-116",
        stadiumGoods: "",
      },
    },
    {
      id: "73898a5c-3c6d-4f54-b889-47ad5eb0505a",
      sku: "A01651C",
      brand: "Converse",
      name: "Converse Chuck Taylor All-Star Pokemon Poke Ball",
      colorway: "White/Black",
      gender: "men",
      silhouette: "Chuck Taylor All Star",
      releaseYear: "2022",
      releaseDate: "2022-12-07",
      retailPrice: 70,
      estimatedMarketValue: 73,
      story:
        "The Pokemon x Converse Chuck Taylor All Star High ‘Poke Ball’ celebrates 25 years of the iconic gaming franchise. An all-over Pokemon print is applied to the white canvas upper, lined in crimson textile and accented with a molded Poke Ball patch on the lateral ankle. Standard Chuck details remain intact, including a rubber toe cap, a circular All Star patch, and winged stitching atop the tongue. The high-top is mounted on a white rubber midsole with black pinstripe detailing and a custom Poke Ball license plate.",
      image: {
        360: [
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img01.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img02.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img03.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img04.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img05.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img06.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img07.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img08.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img09.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img10.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img11.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img12.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img13.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img14.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img15.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img16.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img17.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img18.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img19.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img20.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img21.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img22.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img23.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img24.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img25.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img26.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img27.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img28.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img29.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img30.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img31.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img32.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img33.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img34.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img35.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
          "https://images.stockx.com/360/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Images/Converse-Chuck-Taylor-All-Star-Pokemon-Poke-Ball/Lv2/img36.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653647",
        ],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/067/269/426/original/883848_00.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/067/269/426/original/883848_00.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/067/269/426/original/883848_00.png.png",
      },
      links: {
        stockX:
          "https://stockx.com/converse-chuck-taylor-all-star-pokemon-poke-ball",
        goat: "https://goat.com/sneakers/pokemon-x-chuck-taylor-all-star-high-poke-ball-a01651c",
        flightClub:
          "https://flightclub.com/pokemon-x-chuck-taylor-all-star-high-poke-ball-a01651c",
        stadiumGoods: "",
      },
    },
    {
      id: "56d459c1-0448-4628-b723-8d59962093d8",
      sku: "CU9307-106",
      brand: "Jordan",
      name: "Air Jordan 7 Retro 'Cardinal' 2022",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 7",
      releaseYear: "2022",
      releaseDate: "2022-11-26",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story:
        "The 2022 reissue of the Air Jordan 7 Retro ‘Cardinal’ revives an OG colorway of the silhouette that Michael Jordan wore when he clinched his second NBA championship. The sneaker sports a white leather upper with perforated detailing and a Huarache-like interior sleeve for a snug fit. Branding elements include a ‘23’ heel patch, an embroidered Jumpman on the lateral ankle, and ‘Air Jordan’ lettering on the tongue. Enhanced with hidden Air-sole cushioning, the navy-colored Phylon midsole features angular Cardinal red accents that give the shoe its name.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-7-retro-cardinal-2022-cu9307-106",
        flightClub:
          "https://flightclub.com/air-jordan-7-retro-cardinal-2022-cu9307-106",
        stadiumGoods: "",
      },
    },
    {
      id: "28eaaeda-5cc8-4a1a-a377-602fa78bb3c7",
      sku: "DX2836-001",
      brand: "Jordan",
      name: "Air Jordan 6 Retro 'Metallic Silver'",
      colorway: "Black/Metallic Silver-Black",
      gender: "men",
      silhouette: "Air Jordan 6",
      releaseYear: "2022",
      releaseDate: "2022-11-19",
      retailPrice: 200,
      estimatedMarketValue: 200,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-6-retro-metallic-silver-dx2836-001",
        flightClub:
          "https://flightclub.com/air-jordan-6-retro-metallic-silver-dx2836-001",
        stadiumGoods: "",
      },
    },
    {
      id: "8d3eaa46-2e02-4852-b171-a49b87cc559e",
      sku: "DZ5485-303",
      brand: "Jordan",
      name: "Air Jordan 1 Retro High OG 'Gorge Green'",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-11-12",
      retailPrice: 180,
      estimatedMarketValue: 180,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-high-og-gorge-green-dz5485-303",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-high-og-gorge-green-dz5485-303",
        stadiumGoods: "",
      },
    },
    {
      id: "3efdef6e-8349-4ad6-b4b8-9861ee1c4e39",
      sku: "DZ5485-612",
      brand: "Jordan",
      name: "Air Jordan 1 Retro High OG",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-10-29",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story:
        "The Air Jordan 1 ‘Chicago Reimagined’ brings back the iconic silhouette that started it all. In addition to the OG Chicago-inspired color scheme, the sneaker features an aged aesthetic and a high-cut shape that reflects the look of the original 1985 release. The leather upper combines a white base with a black signature Swoosh and scarlet overlays at the forefoot and heel. A woven Nike tag adorns the nylon tongue, while a retro Wings logo is stamped on the lateral ankle. The high-top is mounted on a rubber cupsole that packs an Air-sole heel unit encapsulated in lightweight polyurethane.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-high-og-dz5485-612",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-high-og-dz5485-612",
        stadiumGoods: "",
      },
    },
    {
      id: "1b899785-9786-4848-b916-db91f20b1028",
      sku: "DX2454-106",
      brand: "Jordan",
      name: "Air Jordan 2 Retro 'Chicago' 2022",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 2",
      releaseYear: "2022",
      releaseDate: "2022-10-22",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story:
        "The 2022 edition of the Air Jordan 2 Retro ‘Chicago’ brings back the legacy silhouette in its original 1986 form. A radical design departure from its predecessor, the sneaker discards Nike Swoosh branding while introducing the Jordan ‘Wings’ logo atop the tongue. Black laces secure a white leather upper appointed with sleek lines, perforated detailing, and a faux lizard skin overlay inspired by luxury footwear. A crimson heel counter provides a contrasting pop of color, while a Nike wordmark decorates the rear collar. Traditional cupsole tooling is replaced by a black polyurethane midsole with encapsulated Air-sole cushioning.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-2-retro-chicago-2022-dx2454-106",
        flightClub:
          "https://flightclub.com/air-jordan-2-retro-chicago-2022-dx2454-106",
        stadiumGoods: "",
      },
    },
    {
      id: "d70fd0c1-7ca2-4cf9-8fe8-8047a19b271b",
      sku: "DH6927-140",
      brand: "Jordan",
      name: "Air Jordan 4 Retro 'Midnight Navy'",
      colorway: "White/Midnight Navy/Light Smoke Grey/Fire Red",
      gender: "men",
      silhouette: "Air Jordan 4",
      releaseYear: "2022",
      releaseDate: "2022-10-01",
      retailPrice: 210,
      estimatedMarketValue: 210,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-4-retro-midnight-navy-dh6927-140",
        flightClub:
          "https://flightclub.com/air-jordan-4-retro-midnight-navy-dh6927-140",
        stadiumGoods: "",
      },
    },
    {
      id: "5ff9333a-7bdc-49fc-8192-0bacdb69a021",
      sku: "DM9036-104",
      brand: "Jordan",
      name: "Jordan 1 High OG Denim (W)",
      colorway: "White/Worn Blue-Metallic Gold",
      gender: "women",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-09-23",
      retailPrice: 170,
      estimatedMarketValue: 260,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/071/460/892/original/DM9036_104.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/071/460/892/original/DM9036_104.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/071/460/892/original/DM9036_104.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-1-high-og-denim-w",
        goat: "https://goat.com/sneakers/wmns-air-jordan-1-high-og-denim-dm9036-104",
        flightClub:
          "https://flightclub.com/wmns-air-jordan-1-high-og-denim-dm9036-104",
        stadiumGoods: "",
      },
    },
    {
      id: "57e1eb3f-7e23-4bfa-a878-8411e751c324",
      sku: "555088-202",
      brand: "Jordan",
      name: "Air Jordan 1 Retro High OG 'Heirloom'",
      colorway: "Vachetta Tan/Black/Sail",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-09-17",
      retailPrice: 170,
      estimatedMarketValue: 470,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-high-og-heirloom-555088-202",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-high-og-heirloom-555088-202",
        stadiumGoods: "",
      },
    },
    {
      id: "b0450a70-1647-40ec-a37f-822677826b37",
      sku: "H03347",
      brand: "adidas",
      name: "adidas Busenitz Vintage Focus Orange",
      colorway: "Focus Orange/Cloud White/Gum",
      gender: "men",
      silhouette: "Busenitz",
      releaseYear: "2022",
      releaseDate: "2022-09-01",
      retailPrice: 85,
      estimatedMarketValue: 121,
      story: "",
      image: {
        360: [
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img01.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img02.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img03.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img04.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img05.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img06.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img07.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img08.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img09.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img10.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img11.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img12.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img13.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img14.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img15.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img16.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img17.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img18.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img19.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img20.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img21.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img22.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img23.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img24.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img25.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img26.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img27.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img28.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img29.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img30.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img31.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img32.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img33.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img34.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img35.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
          "https://images.stockx.com/360/adidas-Busenitz-Vintage-Focus-Orange/Images/adidas-Busenitz-Vintage-Focus-Orange/Lv2/img36.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652209460",
        ],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/065/932/557/original/815843_00.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/065/932/557/original/815843_00.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/065/932/557/original/815843_00.png.png",
      },
      links: {
        stockX: "https://stockx.com/adidas-busenitz-vintage-focus-orange",
        goat: "https://goat.com/sneakers/busenitz-vintage-focus-orange-gum-h03347",
        flightClub:
          "https://flightclub.com/busenitz-vintage-focus-orange-gum-h03347",
        stadiumGoods: "",
      },
    },
    {
      id: "b9906810-1228-4b36-b980-bb3e7ec2a7d1",
      sku: "GY0850",
      brand: "adidas",
      name: "Karlie Kloss x Wmns Trainer XX92 Vegan 'Wonder Mauve'",
      colorway: "Wonder Mauve/Wonder Mauve/Core Black",
      gender: "women",
      silhouette: "Trainer XX92",
      releaseYear: "2022",
      releaseDate: "2022-08-31",
      retailPrice: 90,
      estimatedMarketValue: 90,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/464/686/original/GY0850.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/464/686/original/GY0850.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/464/686/original/GY0850.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/karlie-kloss-x-wmns-trainer-xx92-vegan-wonder-mauve-gy0850",
        flightClub:
          "https://flightclub.com/karlie-kloss-x-wmns-trainer-xx92-vegan-wonder-mauve-gy0850",
        stadiumGoods: "",
      },
    },
    {
      id: "fd280eb4-c925-43dc-a370-4f5e03244a5f",
      sku: "DH7138-006",
      brand: "Jordan",
      name: "Air Jordan 4 Retro 'Black Canvas'",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 4",
      releaseYear: "2022",
      releaseDate: "2022-08-27",
      retailPrice: 210,
      estimatedMarketValue: 210,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-4-retro-black-canvas-dh7138-006",
        flightClub:
          "https://flightclub.com/air-jordan-4-retro-black-canvas-dh7138-006",
        stadiumGoods: "",
      },
    },
    {
      id: "3efcfefa-b4da-4a09-b38f-fb7f24c4774a",
      sku: "414571-164",
      brand: "Jordan",
      name: "Air Jordan 13 Retro 'French Blue'",
      colorway: "White/Fire Red/French Blue/Light Steel Grey",
      gender: "men",
      silhouette: "Air Jordan 13",
      releaseYear: "2022",
      releaseDate: "2022-08-20",
      retailPrice: 200,
      estimatedMarketValue: 200,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-13-retro-french-blue-414571-164",
        flightClub:
          "https://flightclub.com/air-jordan-13-retro-french-blue-414571-164",
        stadiumGoods: "",
      },
    },
    {
      id: "43d56cec-0872-416b-994d-6a182fa305ed",
      sku: "555088-711",
      brand: "Jordan",
      name: "Air Jordan 1 Retro High OG 'Yellow Toe'",
      colorway: "Taxi/Black/Sail",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-08-13",
      retailPrice: 170,
      estimatedMarketValue: 600,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-high-og-yellow-toe-555088-711",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-high-og-yellow-toe-555088-711",
        stadiumGoods: "",
      },
    },
    {
      id: "cba7f51f-09a7-4548-bcdd-b7324a7dc6ee",
      sku: "AQ9129-500",
      brand: "Jordan",
      name: "Wmns Air Jordan 4 Retro 'Canyon Purple'",
      colorway: "Canyon Purple/Anthracite/Alligator/Safety Orange",
      gender: "women",
      silhouette: "Air Jordan 4",
      releaseYear: "2022",
      releaseDate: "2022-08-11",
      retailPrice: 200,
      estimatedMarketValue: 200,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/wmns-air-jordan-4-retro-canyon-purple-aq9129-500",
        flightClub:
          "https://flightclub.com/wmns-air-jordan-4-retro-canyon-purple-aq9129-500",
        stadiumGoods: "",
      },
    },
    {
      id: "06b3cbaf-a28b-4639-b4c2-891ef521ad23",
      sku: "DN3707-160",
      brand: "Jordan",
      name: "Air Jordan 3 Retro 'Fire Red' 2022",
      colorway: "White/Fire Red/Cement Grey/Black",
      gender: "men",
      silhouette: "Air Jordan 3",
      releaseYear: "2022",
      releaseDate: "2022-08-06",
      retailPrice: 210,
      estimatedMarketValue: 210,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-3-retro-fire-red-2022-dn3707-160",
        flightClub:
          "https://flightclub.com/air-jordan-3-retro-fire-red-2022-dn3707-160",
        stadiumGoods: "",
      },
    },
    {
      id: "b1feaaf7-435d-4125-a133-46996e3b25a2",
      sku: "CZ0790-104",
      brand: "Jordan",
      name: "Air Jordan 1 Retro Low OG 'UNC'",
      colorway: "White/Dark Powder Blue/Black",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-07-29",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-low-og-unc-cz0790-104",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-low-og-unc-cz0790-104",
        stadiumGoods: "",
      },
    },
    {
      id: "af454345-2636-4785-ac1a-4b971bc6061c",
      sku: "DJ4891-061",
      brand: "Jordan",
      name: "Wmns Air Jordan 1 High OG 'Chenille Red'",
      colorway: "Light Iron Ore/Varsity Red/Sail",
      gender: "women",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-07-23",
      retailPrice: 170,
      estimatedMarketValue: 350,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/071/390/597/original/DJ4891_061.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/071/390/597/original/DJ4891_061.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/071/390/597/original/DJ4891_061.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/wmns-air-jordan-1-high-og-chenille-red-dj4891-061",
        flightClub:
          "https://flightclub.com/wmns-air-jordan-1-high-og-chenille-red-dj4891-061",
        stadiumGoods: "",
      },
    },
    {
      id: "295991f2-45f4-440f-b2f0-0cf83d20efa3",
      sku: "DM7866-162",
      brand: "Jordan",
      name: "Travis Scott x Air Jordan 1 Low OG 'Reverse Mocha'",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-07-21",
      retailPrice: 0,
      estimatedMarketValue: 2750,
      story:
        "The Travis Scott x Air Jordan 1 Low OG ‘Reverse Mocha’ delivers a twist on the original ‘Mocha’ AJ1 Low from 2019. The upper combines a brown suede base with ivory leather overlays and the Houston rapper’s signature reverse Swoosh on the lateral side, featuring oversized dimensions and a neutral cream finish. Contrasting scarlet accents distinguish a pair of woven Nike Air tongue tags, as well as mismatched Cactus Jack and retro Wings logos embroidered on each heel tab. A vintage off-white rubber midsole is bolstered with encapsulated Nike Air cushioning in the heel and a brown rubber outsole underfoot.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/travis-scott-x-air-jordan-1-low-og-reverse-mocha-dm7866-162",
        flightClub:
          "https://flightclub.com/travis-scott-x-air-jordan-1-low-og-reverse-mocha-dm7866-162",
        stadiumGoods: "",
      },
    },
    {
      id: "4e25246b-4c4e-4c64-98e6-87bbcd2a642e",
      sku: "DO9369-101",
      brand: "Jordan",
      name: "Wmns Air Jordan 1 High OG 'Starfish'",
      colorway: "White/Starfish/Cacao Wow/Sail",
      gender: "women",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-07-21",
      retailPrice: 170,
      estimatedMarketValue: 170,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/wmns-air-jordan-1-high-og-starfish-do9369-101",
        flightClub:
          "https://flightclub.com/wmns-air-jordan-1-high-og-starfish-do9369-101",
        stadiumGoods: "",
      },
    },
    {
      id: "39d48e26-7293-4986-88e8-80cf9e3f4fe9",
      sku: "DX6325-204",
      brand: "Jordan",
      name: "Paris Saint-Germain x Air Jordan 5 Retro Low 'Paname'",
      colorway: "Pumice/Game Royal/Black/Plum/Eclipse/Bright Crimson",
      gender: "men",
      silhouette: "Air Jordan 5",
      releaseYear: "2022",
      releaseDate: "2022-07-16",
      retailPrice: 200,
      estimatedMarketValue: 200,
      story:
        "Paris Saint-Germain and Jordan Brand continue their partnership with a new Air Jordan 5 Retro Low. Details of this generational collaboration can be found all over the shoe, including a tricolor &#39;Paname&#39; tag on the lateral middle panel, a wax seal Jumpman badge on the back heel, and PARIS stitched on the inside of the tongue. A visible Air-sole unit can be found on the black midsole, while a translucent outsole reveals a circular Jumpman PSG logo underneath.",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/paris-saint-germain-x-air-jordan-5-retro-low-paname-dx6325-204",
        flightClub:
          "https://flightclub.com/paris-saint-germain-x-air-jordan-5-retro-low-paname-dx6325-204",
        stadiumGoods: "",
      },
    },
    {
      id: "fc8ae551-7882-469d-9665-1b8e522e16a9",
      sku: "384360-02",
      brand: "Puma",
      name: "Butter Goods x Suede VTG HS 'Whisper White'",
      colorway: "Whisper White/Puma Black",
      gender: "men",
      silhouette: "Suede",
      releaseYear: "2022",
      releaseDate: "2022-07-16",
      retailPrice: 120,
      estimatedMarketValue: 180,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/311/688/original/384360_02.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/311/688/original/384360_02.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/311/688/original/384360_02.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/butter-goods-x-suede-vtg-hs-whisper-white-384360-02",
        flightClub:
          "https://flightclub.com/butter-goods-x-suede-vtg-hs-whisper-white-384360-02",
        stadiumGoods: "",
      },
    },
    {
      id: "1d367e58-ee18-42bc-9fc2-e31ac0c9719c",
      sku: "BLNDS36-GRN",
      brand: "Vans",
      name: "Blends x OG Style 36 LX 'Magic Tape Pack - Green'",
      colorway: "",
      gender: "men",
      silhouette: "Style 36",
      releaseYear: "2022",
      releaseDate: "2022-07-02",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/blends-x-og-style-36-lx-magic-tape-pack-green-blnds36-grn",
        flightClub:
          "https://flightclub.com/blends-x-og-style-36-lx-magic-tape-pack-green-blnds36-grn",
        stadiumGoods: "",
      },
    },
    {
      id: "d7a66231-a476-4573-85eb-a00761e03551",
      sku: "CU9307-081",
      brand: "Jordan",
      name: "Jordan 7 Retro Citrus (2022)",
      colorway: "Black/Citrus-Varsity Red",
      gender: "men",
      silhouette: "Air Jordan 7",
      releaseYear: "2022",
      releaseDate: "2022-07-02",
      retailPrice: 200,
      estimatedMarketValue: 200,
      story:
        "The 2022 edition of the Air Jordan 7 Retro ‘Citrus’ revives a non-OG colorway that was initially released in 2006. Like the original, the upper is constructed from black nubuck with a Huarache-like inner sleeve and contrast orange stitching throughout. The Citrus hue is repeated on the angular ‘23’ heel patch and a Jumpman logo embroidered on the lateral collar. A red webbing pull tab at the heel provides easy on and off. Orange and crimson accents reappear on the black foam midsole, featuring encapsulated Air-sole cushioning for a smooth ride.",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/066/731/059/original/CU9307_081.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/066/731/059/original/CU9307_081.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/066/731/059/original/CU9307_081.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-7-retro-citrus-2022",
        goat: "https://goat.com/sneakers/air-jordan-7-retro-citrus-cu9307-081",
        flightClub:
          "https://flightclub.com/air-jordan-7-retro-citrus-cu9307-081",
        stadiumGoods: "",
      },
    },
    {
      id: "59020ec3-1880-4b34-a985-5da84b5c2be0",
      sku: "GY0851",
      brand: "adidas",
      name: "Karlie Kloss x Wmns Trainer XX92 'Cloud White'",
      colorway: "Cloud White/Cloud White/Core Black",
      gender: "women",
      silhouette: "Trainer XX92",
      releaseYear: "2022",
      releaseDate: "2022-07-01",
      retailPrice: 90,
      estimatedMarketValue: 90,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/464/688/original/GY0851.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/464/688/original/GY0851.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/464/688/original/GY0851.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/karlie-kloss-x-wmns-trainer-xx92-cloud-white-gy0851",
        flightClub:
          "https://flightclub.com/karlie-kloss-x-wmns-trainer-xx92-cloud-white-gy0851",
        stadiumGoods: "",
      },
    },
    {
      id: "bf297c32-b0a9-45ca-89bb-92f15467c5dd",
      sku: "CT8532-008",
      brand: "Jordan",
      name: "Air Jordan 3 Retro 'Desert Elephant'",
      colorway: "",
      gender: "men",
      silhouette: "Air Jordan 3",
      releaseYear: "2022",
      releaseDate: "2022-07-01",
      retailPrice: 0,
      estimatedMarketValue: 660,
      story:
        "The Air Jordan 3 Retro ‘Desert Elephant’ showcases materials and color blocking that stay true to the iconic silhouette’s original 1988 release. The upper is constructed from black tumbled leather with signature elephant-print overlays in a light tan finish. The neutral hue is repeated on the collar, eyestay, and tongue, the latter accented with a crimson Jumpman logo. Supporting the mid-top is a white polyurethane midsole with a visible Air-sole unit nestled under the heel.",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/823/425/original/CT8532_008.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/823/425/original/CT8532_008.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/823/425/original/CT8532_008.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-3-retro-desert-ct8532-008",
        flightClub:
          "https://flightclub.com/air-jordan-3-retro-desert-ct8532-008",
        stadiumGoods: "",
      },
    },
    {
      id: "8deafe2b-abe1-4b12-aed0-406f9574a492",
      sku: "DC1975-001",
      brand: "Nike",
      name: "KD 15 'Beginnings'",
      colorway: "Black/Sanddrift/Aura/Boarder Blue",
      gender: "men",
      silhouette: "KD 15",
      releaseYear: "2022",
      releaseDate: "2022-06-25",
      retailPrice: 150,
      estimatedMarketValue: 150,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/071/019/133/original/DC1975_001.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/071/019/133/original/DC1975_001.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/071/019/133/original/DC1975_001.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/kd-15-beginnings-dc1975-001",
        flightClub: "https://flightclub.com/kd-15-beginnings-dc1975-001",
        stadiumGoods: "",
      },
    },
    {
      id: "aec22a81-65e2-4bf7-8e73-b8a67526e7c7",
      sku: "DO5254-180",
      brand: "Jordan",
      name: "Jordan 2 Retro Maison Chateau Rouge",
      colorway: "Sail/Orange",
      gender: "men",
      silhouette: "Air Jordan 2",
      releaseYear: "2022",
      releaseDate: "2022-06-24",
      retailPrice: 200,
      estimatedMarketValue: 750,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/070/964/437/original/DO5254_180.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/070/964/437/original/DO5254_180.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/070/964/437/original/DO5254_180.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-2-retro-maison-chateau-rouge",
        goat: "https://goat.com/sneakers/maison-chateau-rouge-x-air-jordan-2-united-youth-international-do5254-180",
        flightClub:
          "https://flightclub.com/maison-chateau-rouge-x-air-jordan-2-united-youth-international-do5254-180",
        stadiumGoods: "",
      },
    },
    {
      id: "72c1f386-afd1-4ba3-a960-0a0160f59d4b",
      sku: "DM1200-001",
      brand: "Jordan",
      name: "Jordan 1 Mid SE Zen Master",
      colorway: "Black/Bleached Coral-White",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-23",
      retailPrice: 125,
      estimatedMarketValue: 116,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/070/685/921/original/922195_00.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/070/685/921/original/922195_00.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/070/685/921/original/922195_00.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-1-mid-se-zen-master",
        goat: "https://goat.com/sneakers/air-jordan-1-mid-se-tie-dye-dm1200-001",
        flightClub:
          "https://flightclub.com/air-jordan-1-mid-se-tie-dye-dm1200-001",
        stadiumGoods: "",
      },
    },
    {
      id: "749bf1d7-b705-48ba-bceb-c8cb5e7ab19c",
      sku: "DM6217-001",
      brand: "Jordan",
      name: "Jordan 1 Mid SE Zen Master (TD)",
      colorway: "Black/White/Amethyst Wave/Bleached Coral",
      gender: "toddler",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-23",
      retailPrice: 65,
      estimatedMarketValue: 60,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/070/465/518/original/DM6217_001.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/070/465/518/original/DM6217_001.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/070/465/518/original/DM6217_001.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-1-mid-se-zen-master-td",
        goat: "https://goat.com/sneakers/air-jordan-1-mid-se-td-tie-dye-dm6217-001",
        flightClub:
          "https://flightclub.com/air-jordan-1-mid-se-td-tie-dye-dm6217-001",
        stadiumGoods: "",
      },
    },
    {
      id: "bd1f6851-03af-4792-9995-a2130a4dfdc5",
      sku: "DM6215-001",
      brand: "Jordan",
      name: "Jordan 1 Mid SE Zen Master (PS)",
      colorway: "Black/White/Amethyst Wave/Bleached Coral",
      gender: "preschool",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-23",
      retailPrice: 80,
      estimatedMarketValue: 64,
      story: "",
      image: {
        360: [
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img01.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img02.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img03.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img04.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img05.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img06.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img07.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img08.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img09.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img10.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img11.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img12.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img13.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img14.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img15.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img16.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img17.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img18.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img19.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img20.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img21.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img22.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img23.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img24.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img25.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img26.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img27.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img28.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img29.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img30.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img31.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img32.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img33.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img34.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img35.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-PS/Images/Air-Jordan-1-Mid-SE-Zen-Master-PS/Lv2/img36.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1650653169",
        ],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/069/048/834/original/DM6215_001.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/069/048/834/original/DM6215_001.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/069/048/834/original/DM6215_001.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-1-mid-se-zen-master-ps",
        goat: "https://goat.com/sneakers/air-jordan-1-mid-se-ps-black-amethyst-wave-dm6215-001",
        flightClub:
          "https://flightclub.com/air-jordan-1-mid-se-ps-black-amethyst-wave-dm6215-001",
        stadiumGoods: "",
      },
    },
    {
      id: "d6da3bca-2ca3-4437-be1d-6913d1095423",
      sku: "DM6216-001",
      brand: "Jordan",
      name: "Jordan 1 Mid SE Zen Master (GS)",
      colorway: "Black/White/Amethyst Wave/Bleached Coral",
      gender: "child",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-23",
      retailPrice: 110,
      estimatedMarketValue: 114,
      story: "",
      image: {
        360: [
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img01.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img02.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img03.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img04.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img05.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img06.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img07.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img08.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img09.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img10.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img11.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img12.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img13.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img14.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img15.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img16.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img17.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img18.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img19.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img20.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img21.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img22.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img23.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img24.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img25.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img26.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img27.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img28.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img29.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img30.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img31.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img32.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img33.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img34.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img35.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
          "https://images.stockx.com/360/Air-Jordan-1-Mid-SE-Zen-Master-GS/Images/Air-Jordan-1-Mid-SE-Zen-Master-GS/Lv2/img36.jpg?auto=format,compress&w=559&q=90&dpr=2&updated_at=1652711164",
        ],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/070/389/474/original/917601_00.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/070/389/474/original/917601_00.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/070/389/474/original/917601_00.png.png",
      },
      links: {
        stockX: "https://stockx.com/air-jordan-1-mid-se-zen-master-gs",
        goat: "https://goat.com/sneakers/air-jordan-1-mid-se-gs-tie-dye-dm6216-001",
        flightClub:
          "https://flightclub.com/air-jordan-1-mid-se-gs-tie-dye-dm6216-001",
        stadiumGoods: "",
      },
    },
    {
      id: "7f93ea94-64e6-436f-885b-4dc01e3eccee",
      sku: "DN1790-001",
      brand: "Nike",
      name: "Air Pegasus 83 'Black Cool Grey'",
      colorway: "Black/Cool Grey",
      gender: "men",
      silhouette: "Air Pegasus 83",
      releaseYear: "2022",
      releaseDate: "2022-06-22",
      retailPrice: 100,
      estimatedMarketValue: 190,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/406/951/original/DN1790_001.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/406/951/original/DN1790_001.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/406/951/original/DN1790_001.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-pegasus-83-black-cool-grey-dn1790-001",
        flightClub:
          "https://flightclub.com/air-pegasus-83-black-cool-grey-dn1790-001",
        stadiumGoods: "",
      },
    },
    {
      id: "f14df05b-f1dc-4655-80d6-3192cecbe593",
      sku: "DH8011-100",
      brand: "Nike",
      name: "Air More Uptempo 'White Midnight Navy'",
      colorway: "White/Midnight Navy/White",
      gender: "men",
      silhouette: "Air More Uptempo",
      releaseYear: "2022",
      releaseDate: "2022-06-22",
      retailPrice: 160,
      estimatedMarketValue: 182,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/069/253/319/original/DH8011_100.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/069/253/319/original/DH8011_100.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/069/253/319/original/DH8011_100.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-more-uptempo-white-midnight-navy-dh8011-100",
        flightClub:
          "https://flightclub.com/air-more-uptempo-white-midnight-navy-dh8011-100",
        stadiumGoods: "",
      },
    },
    {
      id: "2c2bc064-a09d-417c-bbef-b8a7e8e4357d",
      sku: "GY6386",
      brand: "Reebok",
      name: "Eames Office x Classic Leather 'Eames Elephant - Cool Aloe'",
      colorway: "Cool Aloe/Cool Aloe/Core Black",
      gender: "men",
      silhouette: "Reebok Classic",
      releaseYear: "2022",
      releaseDate: "2022-06-21",
      retailPrice: 120,
      estimatedMarketValue: 120,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/311/814/original/GY6386.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/311/814/original/GY6386.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/311/814/original/GY6386.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/eames-office-x-classic-leather-eames-elephant-cool-aloe-gy6386",
        flightClub:
          "https://flightclub.com/eames-office-x-classic-leather-eames-elephant-cool-aloe-gy6386",
        stadiumGoods: "",
      },
    },
    {
      id: "4575bd9c-ffbe-4ce3-9ca9-e0590d492a7e",
      sku: "GY6384",
      brand: "Reebok",
      name: "Eames Office x Classic Leather 'Eames Elephant - Vector Red'",
      colorway: "Vector Red/Vector Red/Core Black",
      gender: "men",
      silhouette: "Reebok Classic",
      releaseYear: "2022",
      releaseDate: "2022-06-21",
      retailPrice: 120,
      estimatedMarketValue: 120,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/311/812/original/GY6384.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/311/812/original/GY6384.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/311/812/original/GY6384.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/eames-office-x-classic-leather-eames-elephant-vector-red-gy6384",
        flightClub:
          "https://flightclub.com/eames-office-x-classic-leather-eames-elephant-vector-red-gy6384",
        stadiumGoods: "",
      },
    },
    {
      id: "46cc9bed-a2d3-4b06-914e-583ccd74e16d",
      sku: "DR1413-001",
      brand: "Nike",
      name: "Union LA x Cortez SP 'Off Noir'",
      colorway: "Off Noir/Neptune Green/Mean Green/Off Noir",
      gender: "men",
      silhouette: "Cortez",
      releaseYear: "2022",
      releaseDate: "2022-06-21",
      retailPrice: 130,
      estimatedMarketValue: 1400,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/union-la-x-cortez-black-blue-dr1413-001",
        flightClub:
          "https://flightclub.com/union-la-x-cortez-black-blue-dr1413-001",
        stadiumGoods: "",
      },
    },
    {
      id: "65f161d7-bd65-4505-9a63-3a08d7628096",
      sku: "DR1413-200",
      brand: "Nike",
      name: "Union LA x Cortez SP 'Grain'",
      colorway: "Grain/Pink Clay/Dutch Green/Bicycle Yellow/Blustery",
      gender: "men",
      silhouette: "Cortez",
      releaseYear: "2022",
      releaseDate: "2022-06-21",
      retailPrice: 130,
      estimatedMarketValue: 1290,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/406/959/original/DR1413_200.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/406/959/original/DR1413_200.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/406/959/original/DR1413_200.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/union-la-x-cortez-red-beige-dr1413-200",
        flightClub:
          "https://flightclub.com/union-la-x-cortez-red-beige-dr1413-200",
        stadiumGoods: "",
      },
    },
    {
      id: "72c8d967-4847-465f-be71-cd5edb01859c",
      sku: "GY6385",
      brand: "Reebok",
      name: "Eames Office x Classic Leather 'Eames Elephant - Seaside Grey'",
      colorway: "Seaside Grey/Seaside Grey/Core Black",
      gender: "men",
      silhouette: "Reebok Classic",
      releaseYear: "2022",
      releaseDate: "2022-06-21",
      retailPrice: 120,
      estimatedMarketValue: 120,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/311/813/original/GY6385.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/311/813/original/GY6385.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/311/813/original/GY6385.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/eames-office-x-classic-leather-eames-elephant-seaside-grey-gy6385",
        flightClub:
          "https://flightclub.com/eames-office-x-classic-leather-eames-elephant-seaside-grey-gy6385",
        stadiumGoods: "",
      },
    },
    {
      id: "43d54fe4-618c-40aa-9d68-e7b83ed9b190",
      sku: "CT8532-105",
      brand: "Jordan",
      name: "Air Jordan 3 Retro 'Dark Iris'",
      colorway: "White/Black/Dark Iris/Cement Grey",
      gender: "men",
      silhouette: "Air Jordan 3",
      releaseYear: "2022",
      releaseDate: "2022-06-18",
      retailPrice: 200,
      estimatedMarketValue: 401,
      story:
        "The Air Jordan 3 Retro ‘Dark Iris’ brings a revitalized color palette to the hardwood classic that introduced visible Air cushioning to the Jordan franchise. The sneaker utilizes a white tumbled leather upper with signature elephant print overlays in a dark grey finish. Violet accents make their way to the eyelets, perforated collar and the rear of the polyurethane midsole. Jumpman branding hits adorn the leather tongue and molded heel overlay. Underfoot, a grey rubber outsole provides durable traction.",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/071/312/577/original/CT8532_105.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/071/312/577/original/CT8532_105.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/071/312/577/original/CT8532_105.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-3-retro-dark-iris-ct8532-105",
        flightClub:
          "https://flightclub.com/air-jordan-3-retro-dark-iris-ct8532-105",
        stadiumGoods: "",
      },
    },
    {
      id: "0c2d8214-72e3-4ddc-8260-946a834d1c23",
      sku: "BLNDS36-WHT",
      brand: "Vans",
      name: "Blends x OG Style 36 LX 'Magic Tape Pack - Marshmallow'",
      colorway: "",
      gender: "men",
      silhouette: "Style 36",
      releaseYear: "2022",
      releaseDate: "2022-06-17",
      retailPrice: 0,
      estimatedMarketValue: 0,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/blends-x-og-style-36-lx-magic-tape-pack-marshmallow-blnds36-wht",
        flightClub:
          "https://flightclub.com/blends-x-og-style-36-lx-magic-tape-pack-marshmallow-blnds36-wht",
        stadiumGoods: "",
      },
    },
    {
      id: "6b0b50c0-8589-4d5a-bcf0-36a5baeb7c51",
      sku: "CZ0790-061",
      brand: "Jordan",
      name: "Air Jordan 1 Retro Low OG 'Bleached Coral'",
      colorway: "Black/Bleached Coral/White/Grey Fog",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-17",
      retailPrice: 130,
      estimatedMarketValue: 179,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/774/945/original/CZ0790_061.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/774/945/original/CZ0790_061.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/774/945/original/CZ0790_061.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-low-og-bleached-coral-cz0790-061",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-low-og-bleached-coral-cz0790-061",
        stadiumGoods: "",
      },
    },
    {
      id: "b80b89bb-0521-40ad-8994-e4ab10fa07db",
      sku: "DM1206-163",
      brand: "Jordan",
      name: "Air Jordan 1 Low FlyEase 'White Gym Red'",
      colorway: "White/Black/Gym Red",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-16",
      retailPrice: 130,
      estimatedMarketValue: 216,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/004/107/original/DM1206_163.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/004/107/original/DM1206_163.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/004/107/original/DM1206_163.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-low-flyease-white-gym-red-dm1206-163",
        flightClub:
          "https://flightclub.com/air-jordan-1-low-flyease-white-gym-red-dm1206-163",
        stadiumGoods: "",
      },
    },
    {
      id: "44e5358c-ff58-4dea-a66a-b88cf300aef1",
      sku: "384487-02",
      brand: "Puma",
      name: "Minecraft x Suede Infant 'Grey Violet Block'",
      colorway: "Grey Violet/Blue Atoll",
      gender: "infant",
      silhouette: "Suede",
      releaseYear: "2022",
      releaseDate: "2022-06-12",
      retailPrice: 50,
      estimatedMarketValue: 50,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/464/590/original/384487_02.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/464/590/original/384487_02.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/464/590/original/384487_02.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/minecraft-x-suede-infant-grey-violet-block-384487-02",
        flightClub:
          "https://flightclub.com/minecraft-x-suede-infant-grey-violet-block-384487-02",
        stadiumGoods: "",
      },
    },
    {
      id: "cee7f5f7-4f68-4f7c-b59c-95104c6a649c",
      sku: "555088-702",
      brand: "Jordan",
      name: "Air Jordan 1 Retro High OG 'Visionaire'",
      colorway: "Volt/Black/Sail",
      gender: "men",
      silhouette: "Air Jordan 1",
      releaseYear: "2022",
      releaseDate: "2022-06-11",
      retailPrice: 170,
      estimatedMarketValue: 400,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/air-jordan-1-retro-high-og-visionaire-555088-702",
        flightClub:
          "https://flightclub.com/air-jordan-1-retro-high-og-visionaire-555088-702",
        stadiumGoods: "",
      },
    },
    {
      id: "21cd5d08-5142-4dfa-ac4f-c59ca8376a81",
      sku: "GY6391",
      brand: "Reebok",
      name: "Eames Office x Classic Leather 'Rosewood'",
      colorway: "Dark Brown/Dark Brown/Dark Brown",
      gender: "men",
      silhouette: "Reebok Classic",
      releaseYear: "2022",
      releaseDate: "2022-06-10",
      retailPrice: 0,
      estimatedMarketValue: 79,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/004/136/original/GY6391.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/004/136/original/GY6391.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/004/136/original/GY6391.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/eames-office-x-classic-leather-molded-plywood-chair-gy6391",
        flightClub:
          "https://flightclub.com/eames-office-x-classic-leather-molded-plywood-chair-gy6391",
        stadiumGoods: "",
      },
    },
    {
      id: "37bbe74b-f737-4b6c-a2ec-e773ab516890",
      sku: "GY6393",
      brand: "Reebok",
      name: "Eames Office x Classic Leather 'Coloring Toy'",
      colorway: "Footwear White/Footwear White/Core Black",
      gender: "men",
      silhouette: "Reebok Classic",
      releaseYear: "2022",
      releaseDate: "2022-06-10",
      retailPrice: 0,
      estimatedMarketValue: 79,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/072/004/137/original/GY6393.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/072/004/137/original/GY6393.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/072/004/137/original/GY6393.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/eames-office-x-classic-leather-the-colouring-gy6393",
        flightClub:
          "https://flightclub.com/eames-office-x-classic-leather-the-colouring-gy6393",
        stadiumGoods: "",
      },
    },
    {
      id: "87befbb2-0d6d-451e-8f0d-be74f2f12cd2",
      sku: "385820-01",
      brand: "Puma",
      name: "Superman x RS-Z",
      colorway: "Bluemazing",
      gender: "men",
      silhouette: "RS-Z",
      releaseYear: "2022",
      releaseDate: "2022-06-10",
      retailPrice: 120,
      estimatedMarketValue: 120,
      story: "",
      image: {
        360: [],
        original: "",
        small: "",
        thumbnail: "",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/superman-x-rs-z-385820-01",
        flightClub: "https://flightclub.com/superman-x-rs-z-385820-01",
        stadiumGoods: "",
      },
    },
    {
      id: "18ed5d55-8101-4e75-9912-85d72e22be35",
      sku: "DJ9946-100",
      brand: "Nike",
      name: "Wmns Air Force 1 PLT.AF.ORM 'Triple White'",
      colorway: "White/Summit White/White/White",
      gender: "women",
      silhouette: "Air Force 1",
      releaseYear: "2022",
      releaseDate: "2022-06-09",
      retailPrice: 120,
      estimatedMarketValue: 114,
      story: "",
      image: {
        360: [],
        original:
          "https://image.goat.com/attachments/product_template_pictures/images/071/776/022/original/DJ9946_100.png.png",
        small:
          "https://image.goat.com/750/attachments/product_template_pictures/images/071/776/022/original/DJ9946_100.png.png",
        thumbnail:
          "https://image.goat.com/375/attachments/product_template_pictures/images/071/776/022/original/DJ9946_100.png.png",
      },
      links: {
        stockX: "",
        goat: "https://goat.com/sneakers/wmns-air-force-1-plt-af-orm-triple-white-dj9946-100",
        flightClub:
          "https://flightclub.com/wmns-air-force-1-plt-af-orm-triple-white-dj9946-100",
        stadiumGoods: "",
      },
    },
  ],
};

export default data;
